all:
	ghc PortraitFormatter.hs -O2 -o PortraitFormatter -i../

PortraitFormatter:
	ghc PortraitFormatter.hs -O2 -o PortraitFormatter -i../

Profile:
	ghc PortraitFormatter.hs -O2 -i../ -prof -fprof-auto -rtsopts

clean:
	rm -rf *.hi
	rm -rf *.o

remove:
	rm -f PortraitFormatter


