#ifndef __PARAMS__
#define __PARAMS__

#define CAMERA_MIN_HEIGHT 0x20
#define CAMERA_NUM_STEPS 10
#define CAMERA_Z_STEP 0x20
#define CAMERA_MAX_HEIGHT CAMERA_MIN_HEIGHT + ((CAMERA_NUM_STEPS-1) * CAMERA_Z_STEP)

#define HORIZON 110//130

#define MODE5_HEIGHT 128
#define MODE5_WIDTH 160

#define SCALING_FACTOR 4

#endif